-- USERS TABLE
CREATE TABLE Users (
    UserID BIGSERIAL PRIMARY KEY,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL
);

-- PREFERENCES TABLE
CREATE TABLE Preferences (
    PreferenceID TEXT PRIMARY KEY, -- UUID as TEXT, generated by application
    UserID BIGINT NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    HealthAdvice BOOLEAN DEFAULT FALSE,
    FinanceAdvice BOOLEAN DEFAULT FALSE,
    DailyTasks BOOLEAN DEFAULT FALSE
);

-- HEALTH DETAILS TABLE
CREATE TABLE HealthDetails (
    HealthID BIGSERIAL PRIMARY KEY,
    UserID BIGINT NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    Age INTEGER CHECK (Age >= 0),
    Height NUMERIC(5,2), -- in cm
    Weight NUMERIC(5,2), -- in kg
    ActivityLevel TEXT CHECK (ActivityLevel IN ('low', 'moderate', 'high')),
    HeartRate INTEGER,
    GoalWeight NUMERIC(5,2),
    GeneralGoal TEXT
);